### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [yokesh-ks/ToolEmpire#23]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by yokesh-ks** [comment]
Hi @SkyBulk 

Thank you for your interest in my project! I appreciate your feedback and I'm definitely open to adding a license to the repository to make it more clear and accessible to others.

I'll take your suggestion into consideration and make sure to choose a suitable open-source license that aligns with the goals and intentions of the project. In the meantime, if you have any specific licenses in mind or any other suggestions regarding the project, please feel free to share them. Your input is valuable, and I'm always open to improving the project.

Thanks again for reaching out and for your interest in the project!

Best regards,
@yokesh-ks

**Comment by SkyBulk** [comment]
I was thinking on some MIT or apache2 alike licensing due permissive

**Comment by yokesh-ks** [comment]
I've added the MIT License. Thanks for your suggestion!
